"""Collect every run's `result.json` into one table.

Runs land in `results/v1.1/<run_id>/result.json` in a fixed schema, which means the results
table is generated rather than hand-maintained -- so it cannot drift from what was actually
measured, and a run that was never finished shows up as missing instead of as a stale row.

    python scripts/90_report.py               # markdown table to stdout
    python scripts/90_report.py --write       # also refresh results/v1.1/RESULTS.md
"""

import json

from .paths import RESULTS

COLUMNS = [
    ("run_id", "run", "{}"),
    ("arch", "arch", "{}"),
    ("_tonic", "tonic", "{}"),
    ("_sep", "sep", "{}"),
    ("_prior", "DB prior", "{}"),
    ("_split", "split", "{}"),
    ("_top1", "top-1", "{:.3f}"),
    ("_top5", "top-5", "{:.3f}"),
    ("_mrr", "MRR", "{:.3f}"),
    ("_f1", "macro-F1", "{:.3f}"),
    ("_vote", "video", "{:.3f}"),
    ("_test", "**test top-1**", "{}"),
    ("_mins", "min", "{:.0f}"),
]


def load_runs(results_dir=None):
    root = results_dir or RESULTS
    runs = []
    for f in sorted(root.glob("*/result.json")):
        try:
            runs.append(json.loads(f.read_text()))
        except json.JSONDecodeError:
            print(f"  skipping unreadable {f}")
    return runs


def _flatten(r):
    cfg, m = r.get("config", {}), r.get("metrics", {})
    tonic = []
    if cfg.get("tonic") == "normalise":
        tonic.append("audio")
    if cfg.get("tonic_mode") == "condition":
        tonic.append("FiLM")
    if cfg.get("shuffle_tonics"):
        tonic.append("SHUFFLED")
    prior = []
    if cfg.get("graded_alpha"):
        prior.append(f"graded {cfg['graded_alpha']}")
    if cfg.get("aux_weight"):
        prior.append(f"aux {cfg['aux_weight']}")
    test = r.get("test", {}).get("metrics", {}).get("top1")
    return {
        **r,
        "_tonic": "+".join(tonic) or "-",
        "_sep": cfg.get("separate") or "-",
        "_prior": ", ".join(prior) or "-",
        "_split": r.get("split", "?").replace("grouped-", ""),
        "_top1": m.get("top1", float("nan")),
        "_top5": m.get("top5", float("nan")),
        "_mrr": m.get("mrr", float("nan")),
        "_f1": m.get("macro_f1", float("nan")),
        "_vote": m.get("video_vote", float("nan")),
        "_test": f"**{test:.3f}**" if test is not None else "-",
        "_mins": r.get("wall_clock_s", 0) / 60.0,
    }


def markdown_table(runs, sort_by="_top1"):
    rows = sorted((_flatten(r) for r in runs), key=lambda r: -r.get(sort_by, 0))
    out = ["| " + " | ".join(h for _k, h, _f in COLUMNS) + " |",
           "|" + "|".join("---" for _ in COLUMNS) + "|"]
    for r in rows:
        cells = [fmt.format(r.get(key)) for key, _h, fmt in COLUMNS]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def write_results_md(runs, path=None):
    path = path or (RESULTS / "RESULTS.md")
    body = [
        "# Results - dataset v1.1",
        "",
        "Generated by `scripts/90_report.py` from every `results/v1.1/*/result.json`. "
        "Do not hand-edit; re-run the script.",
        "",
        "Chance = 0.020. `split` is how the non-test column was measured: `val` is one "
        "video-grouped 20 % split of the 1810 train clips, `Nfold-cv` is pooled "
        "out-of-fold predictions over all of them. The **test** column is the held-out 150 "
        "clips, scored once.",
        "",
        markdown_table(runs),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(body))
    return path
